services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crawler:
    build: .
    container_name: crawler
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    command: tail -f /dev/null  # Эта команда поддержит контейнер в рабочем состоянии
    stdin_open: true  # Это открывает интерактивный режим
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
